### ISSUE TITLE
uninitialized constant Chef::Resource::Haproxy::Proxy

### ISSUE THREAD

**Issue by akashihi** [nathwill/chef-haproxy-ng#16]
Hello!

I tried your recipe with:

mysql_members = search(:node, 'recipes:jako').map do |s|
  {
    'name' => s.name,
    'address' => s.ipaddress,
    'port' => 3306,
    'config' => 'maxconn 500 check fall 2 inter 1000 rise 5 backup'
  }
end

haproxy_listen 'mysql' do
  mode 'tcp'
  description 'mysql pool'
  balance 'leastconn'
  source node['ipaddress']
  bind '127.0.0.1:3307'
  servers mysql_members
  config [
    'option mysql-check user haproxy'
  ]
end

include_recipe 'haproxy-ng'

and it failed with:

================================================================================
Recipe Compile Error in /var/cache/chef/cookbooks/jako/recipes/default.rb
================================================================================

NameError
---------
uninitialized constant Chef::Resource::Haproxy::Proxy

Cookbook Trace:
---------------
  /var/cache/chef/cookbooks/haproxy-ng/libraries/chef_haproxy_proxy.rb:56:in `block in config'
  /var/cache/chef/cookbooks/haproxy-ng/libraries/chef_haproxy_proxy.rb:50:in `config'
  /var/cache/chef/cookbooks/jako/recipes/default.rb:23:in `from_file'

Relevant File Content:
----------------------
/var/cache/chef/cookbooks/haproxy-ng/libraries/chef_haproxy_proxy.rb:

 49:      def config(arg = nil)
 50:        set_or_return(
 51:          :config, arg,
 52:          :kind_of => Array,
 53:          :default => [],
 54:          :callbacks => {
 55:            "is a valid #{type} config" => lambda do |spec|
 56>>             !verify || Haproxy::Proxy.valid_config?(spec, type)
 57:            end
 58:          }
 59:        )
 60:      end
 61:
 62:      def verify(arg = nil)
 63:        set_or_return(
 64:          :verify, arg,
 65:          :kind_of => [TrueClass, FalseClass],

On [2015-06-01T13:57:08+03:00] INFO: *** Chef 12.3.0 ***

What i'm doing wrong? :)

**Comment by nathwill** [comment]
hey @akashihi, taking a look at this now... can you tell me which version of the cookbook you're using?

**Comment by nathwill** [comment]
@akashihi hmm, having some trouble replicating with the latest version of the cookbook, but i just did a pretty massive re-organization on the library files, so it wouldn't surprise me if something was actually broken...

is this cookbook anywhere i can look at, or can you set up a public repo with a replicating cookbook i can go stare at to test?

here's the test cookbook i set up to test against and the results of the converge

```bash
[nathwill@wyrd haproxy-test]$ kitchen converge cent
-----> Starting Kitchen (v1.4.0)
-----> Converging <default-centos-65>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-centos-65>
       Starting Chef Client, version 12.3.0
       [2015-06-01T19:38:02+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["haproxy-test::default"]
       Synchronizing Cookbooks:
         - haproxy-test
         - apt
         - ark
         - windows
         - 7-zip
         - haproxy-ng
         - chef_handler
       Compiling Cookbooks...
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_instance.rb:24: warning: already initialized constant Haproxy::Instance::CONFIG_KEYWORDS
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_instance.rb:24: warning: previous definition of CONFIG_KEYWORDS was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_instance.rb:54: warning: already initialized constant Haproxy::Instance::TUNING_KEYWORDS
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_instance.rb:54: warning: previous definition of TUNING_KEYWORDS was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:32: warning: already initialized constant Haproxy::Proxy::MODES
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:32: warning: previous definition of MODES was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:34: warning: already initialized constant Haproxy::Proxy::KEYWORD_PEERS
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:34: warning: previous definition of KEYWORD_PEERS was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:35: warning: already initialized constant Haproxy::Proxy::KEYWORD_USERLIST
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:35: warning: previous definition of KEYWORD_USERLIST was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:36: warning: already initialized constant Haproxy::Proxy::KEYWORD_ALL
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:36: warning: previous definition of KEYWORD_ALL was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:37: warning: already initialized constant Haproxy::Proxy::KEYWORD_DEFAULTS_FRONTEND
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:37: warning: previous definition of KEYWORD_DEFAULTS_FRONTEND was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:38: warning: already initialized constant Haproxy::Proxy::KEYWORD_DEFAULTS_BACKEND
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:38: warning: previous definition of KEYWORD_DEFAULTS_BACKEND was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:39: warning: already initialized constant Haproxy::Proxy::KEYWORD_FRONTEND
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:39: warning: previous definition of KEYWORD_FRONTEND was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:40: warning: already initialized constant Haproxy::Proxy::KEYWORD_BACKEND
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:40: warning: previous definition of KEYWORD_BACKEND was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:41: warning: already initialized constant Haproxy::Proxy::KEYWORD_NON_DEFAULTS
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:41: warning: previous definition of KEYWORD_NON_DEFAULTS was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:43: warning: already initialized constant Haproxy::Proxy::KEYWORD_MATRIX
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy.rb:43: warning: previous definition of KEYWORD_MATRIX was here
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy_backend.rb:25: warning: already initialized constant Haproxy::Proxy::Backend::BALANCE_ALGORITHMS
       /tmp/kitchen/cache/cookbooks/haproxy-ng/libraries/haproxy_proxy_backend.rb:25: warning: previous definition of BALANCE_ALGORITHMS was here
       Converging 5 resources
       Recipe: haproxy-test::default
       
         Recipe: <Dynamically Defined Resource>
       
             - create new file /tmp/kitchen/cache/haproxy.listen.mysql.cfg
             - update content in file /tmp/kitchen/cache/haproxy.listen.mysql.cfg from none to f846dd
             --- /tmp/kitchen/cache/haproxy.listen.mysql.cfg	2015-06-01 19:38:02.986490489 +0000
             +++ /tmp/kitchen/cache/.haproxy-listen-mysql20150601-2498-1fdjxt4	2015-06-01 19:38:02.985489999 +0000
             @@ -1 +1,9 @@
             +listen mysql
             +  bind 127.0.0.1:3307
             +  balance leastconn
             +  mode tcp
             +  option mysql-check user haproxy
             +  description mysql pool
             +  source 10.0.2.15
       
             - restore selinux security context
         
       Recipe: haproxy-ng::install
       
           - install version 1.5.2-2.el6 of package haproxy
       Recipe: haproxy-ng::default
         * haproxy_instance[haproxy] action create
         Recipe: <Dynamically Defined Resource>
       
             - update content in file /etc/haproxy/haproxy.cfg from f4bd99 to 4e92d7
             --- /etc/haproxy/haproxy.cfg	2014-09-03 14:45:17.000000000 +0000
             +++ /tmp/chef-rendered-template20150601-2498-s2o4j7	2015-06-01 19:38:14.557272955 +0000
             @@ -1,87 +1,18 @@
             -#---------------------------------------------------------------------
             -# Example configuration for a possible web application.  See the
             -# full configuration options online.
             -#
             -#   http://haproxy.1wt.eu/download/1.4/doc/configuration.txt
             -#
             -#---------------------------------------------------------------------
             -
             -#---------------------------------------------------------------------
             -# Global settings
             -#---------------------------------------------------------------------
             +# Generated by Chef
             +# Changes will be overwritten!
       global
             -    # to have these messages end up in /var/log/haproxy.log you will
             -    # need to:
             -    #
             -    # 1) configure syslog to accept network log events.  This is done
             -    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
             -    #    /etc/sysconfig/syslog
             -    #
             -    # 2) configure local2 events to go to the /var/log/haproxy.log
             -    #   file. A line like the following can be added to
             -    #   /etc/sysconfig/syslog
             -    #
             -    #    local2.*                       /var/log/haproxy.log
             -    #
             -    log         127.0.0.1 local2
             +  daemon
             +  user haproxy
             +  group haproxy
             +  pidfile /var/run/haproxy.pid
             +  maxconn 50000
       
             -    chroot      /var/lib/haproxy
             -    pidfile     /var/run/haproxy.pid
             -    maxconn     4000
             -    user        haproxy
             -    group       haproxy
             -    daemon
             -
             -    # turn on stats unix socket
             -    stats socket /var/lib/haproxy/stats
             -
             -#---------------------------------------------------------------------
             -# common defaults that all the 'listen' and 'backend' sections will
             -# use if not designated in their block
             -#---------------------------------------------------------------------
             -defaults
             -    mode                    http
             -    log                     global
             -    option                  httplog
             -    option                  dontlognull
             -    option http-server-close
             -    option forwardfor       except 127.0.0.0/8
             -    option                  redispatch
             -    retries                 3
             -    timeout http-request    10s
             -    timeout queue           1m
             -    timeout connect         10s
             -    timeout client          1m
             -    timeout server          1m
             -    timeout http-keep-alive 10s
             -    timeout check           10s
             -    maxconn                 3000
             -
             -#---------------------------------------------------------------------
             -# main frontend which proxys to the backends
             -#---------------------------------------------------------------------
             -frontend  main *:5000
             -    acl url_static       path_beg       -i /static /images /javascript /stylesheets
             -    acl url_static       path_end       -i .jpg .gif .png .css .js
             -
             -    use_backend static          if url_static
             -    default_backend             app
             -
             -#---------------------------------------------------------------------
             -# static backend for serving up images, stylesheets and such
             -#---------------------------------------------------------------------
             -backend static
             -    balance     roundrobin
             -    server      static 127.0.0.1:4331 check
             -
             -#---------------------------------------------------------------------
             -# round robin balancing between the various backends
             -#---------------------------------------------------------------------
             -backend app
       ndrobin
             -    server  app1 127.0.0.1:5001 check
             -    server  app2 127.0.0.1:5002 check
             -    server  app3 127.0.0.1:5003 check
             -    server  app4 127.0.0.1:5004 check
             -
             +listen mysql
             +  bind 127.0.0.1:3307
             +  balance leastconn
             +  mode tcp
             +  option mysql-check user haproxy
             +  description mysql pool
             +  source 10.0.2.15
       
             - restore selinux security context
         
       Recipe: haproxy-ng::service
         * cookbook_file[/etc/default/haproxy] action create (skipped due to only_if)
       
           - enable service service[haproxy]
       
           - start service service[haproxy]
       
           - reload service service[haproxy]
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 8/8 resources updated in 13.767799047 seconds
       Finished converging <default-centos-65> (0m20.83s).
-----> Kitchen is finished. (0m21.15s)
[nathwill@wyrd haproxy-test]$ cat attributes/default.rb 

default['haproxy']['proxies'] = %w( mysql )
[nathwill@wyrd haproxy-test]$ cat metadata.rb 
name 'haproxy-test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures haproxy-test'
long_description 'Installs/Configures haproxy-test'
version '0.1.0'

depends 'haproxy-ng'
[nathwill@wyrd haproxy-test]$ cat recipes/default.rb 
#
# Cookbook Name:: haproxy-test
# Recipe:: default
#
# Copyright (c) 2015 The Authors, All Rights Reserved.

mysql_members = [
  {
    'name' => 'mysql01',
    'address' => '1.2.3.4',
    'port' => 3306,
    'config' => 'maxconn 500 check fall 2 inter 1000 rise 5 backup'
  }
]

haproxy_listen 'mysql' do
  mode 'tcp'
  description 'mysql pool'
  balance 'leastconn'
  source node['ipaddress']
  bind '127.0.0.1:3307'
  servers mysql_members
  config [
    'option mysql-check user haproxy'
  ]
end

include_recipe 'haproxy-ng'
```

**Comment by nathwill** [comment]
oh, did you add "depends 'haproxy-ng'" to your metadata?

**Comment by akashihi** [comment]
Sorry for the delay. I'm using 'haproxy-ng', '~> 0.5.0', i've added depends ;) and i'll create test cookbook in a half of hour

**Comment by akashihi** [comment]
https://github.com/akashihi/haproxytest just 'vagrant up'

**Comment by nathwill** [comment]
so i wasn't replicating an uninitialized constant error with that cookbook, but i did see a (legitimate) validation error, due to the use of symbols for the server hash keys instead of strings, and also a service start failure because node['haproxy']['proxies'] defaults to an empty array, and the linked wrapper cookbook doesn't override it. 

if you're going to use the default recipe from the haproxy-ng cookbook, you'll want to make sure you set the config, tuning and proxies attributes (see [attributes/default.rb](https://github.com/nathwill/chef-haproxy-ng/blob/master/attributes/default.rb#L21-L30)), which are used to configure the default `haproxy_instance[haproxy]` resource [here](https://github.com/nathwill/chef-haproxy-ng/blob/master/recipes/default.rb#L21-L29).

**Comment by nathwill** [comment]
@akashihi in any case, please do let me know if you continue to experience errors after making the above changes!

**Comment by akashihi** [comment]
Sorry for the delayed answer, everything looks great now. Thank you :)

**Comment by nathwill** [comment]
No worries, glad to hear it!
